* fix build error under GCC
..\include/lipp/lipp.hpp: In instantiation of 'size_t lipp::size(const T&) [with T = char [256]; size_t = long long unsigned int]':
..\include/lipp/lipp.hpp:399:36:   required from 'bool lipp::preprocessor<T>::include_file(lipp::preprocessor<T>::string_view_t, bool) [with T = lipp::preprocessor_traits<char, std::__cxx11::basic_string<char>, std::basic_string_view<char>, std::vector>; lipp::preprocessor<T>::string_view_t = std::basic_string_view<char>]'
..\include/lipp/lipp.hpp:212:81:   required from 'bool lipp::preprocessor<T>::include_file(lipp::preprocessor<T>::string_view_t) [with T = lipp::preprocessor_traits<char, std::__cxx11::basic_string<char>, std::basic_string_view<char>, std::vector>; lipp::preprocessor<T>::string_view_t = std::basic_string_view<char>]'
D:\code\lipp\test\test.cpp:12:36:   required from here
..\include/lipp/lipp.hpp:118:75: error: request for member 'size' in 'container', which is of non-class type 'const char [256]'
  118 | inline size_t size( const T &container ) LIPP_NOEXCEPT { return container.size(); }
      |                                                                 ~~~~~~~~~~^~~~
Process terminated with status 1 (0 minute(s), 0 second(s))
1 error(s), 25 warning(s) (0 minute(s), 0 second(s))